### ISSUE TITLE
Use BehaviorSubject instead of ReplaySubject(1) in back/populate-db

### ISSUE THREAD

**Issue by Xartok** [kuroidoruido/Collektor#1]
[L179](https://github.com/kuroidoruido/Collektor/blob/master/back/populate-db.js#L179) of back/populate-db.js, for rootAuth$, what you want is better expressed by BehaviorSubject, or maybe AsyncSubject.
See [Behavior vs Replay Subject](https://medium.com/javascript-everyday/behaviorsubject-vs-replaysubject-1-beware-of-edge-cases-b361153d9ccf) and [Behavior, Replay and Async Subject](https://medium.com/@luukgruijs/understanding-rxjs-behaviorsubject-replaysubject-and-asyncsubject-8cc061f1cfc0)

**Comment by kuroidoruido** [comment]
After some reading and testing, I used an AsyncSubject to replace the ReplaySubject(1).

BehaviorSubject need to be initiated, otherwise, before first value push, it will give to subscriber an undefined value. I need a Subject that give nothing until the first value is pushed, what AsyncSubject does.
